/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author Office
 */
public class Main_form extends javax.swing.JFrame {
    JasperReport JR;
    JasperPrint JP;
    Map<String, Object> param = new HashMap<String, Object>(2);
    JasperDesign JD;
    Connection con= new config().configDB();
    /**
     * Creates new form Main_form
     */
    public Main_form() {
        initComponents();
        String log4jConfPath = "log4j.properties";
        PropertyConfigurator.configure(log4jConfPath); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BARANG");

        jButton1.setText("Tampilkan Laporan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(269, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int pilihan= JOptionPane.showConfirmDialog(null, "TAMPILKAN LAPORAN ?","PERINGATAN !!!",JOptionPane.YES_OPTION);
            if(pilihan==JOptionPane.YES_OPTION){
                File JASPERE = new File("src/Main/Lap_brg.jrxml");
                JasperDesign JD = JRXmlLoader.load(JASPERE);


                SimpleDateFormat newDateFormat = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat newDateFormat_dua = new SimpleDateFormat("dd-MM-yyyy");
                //String combo = (String) combo_kategori.getSelectedItem();
                //String  tgla= String.valueOf(newDateFormat.format(combo_tanggal_awal.getDate()));
                //String  tglb= String.valueOf(newDateFormat.format(combo_tgl_akhir.getDate()));
                //String  tglaa= String.valueOf(newDateFormat_dua.format(combo_tanggal_awal.getDate()));
                //String  tglbb= String.valueOf(newDateFormat_dua.format(combo_tgl_akhir.getDate()));
                //param.put("kategori", combo);
               // param.put("tgl_a", tgla);
                //param.put("tgl_b", tglb);
                //param.put("tawal", tglaa);
                //param.put("takhir", tglbb);

                JR = JasperCompileManager.compileReport(JD);
                JP =JasperFillManager.fillReport(JR, param,con);

                JRViewer jv = new JRViewer(JP);
                jv.setOpaque(true);
                jv.setVisible(true);

                jScrollPane1.add(jv);
                jScrollPane1.setViewportView(jv);
                }
                } catch (HeadlessException | JRException e) {
                    JOptionPane.showMessageDialog(null,"error :" +e.getMessage());
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
